---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: northamerica-northeast2-docker.pkg.dev/ferrous-iridium-415220/charlie-cohere-test/frontend:extra
        ports:
        - name: http
          containerPort: 3000
        env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: ADMIN_USER
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: ADMIN_PASSWORD
          - name: PGHOST
            value: postgres-service
          - name: PGDATABASE
            value: cohere
